# Generated by Django 5.0 on 2023-12-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='API.item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка'),
        ),
    ]
