# Generated by Django 5.0 on 2023-12-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.AddField(
            model_name='discount',
            name='order',
            field=models.ManyToManyField(to='API.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='tax',
            name='order',
            field=models.ManyToManyField(to='API.order', verbose_name='Заказ'),
        ),
    ]
