# Generated by Django 5.0 on 2023-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_discount_order_remove_tax_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(blank=True, null=True, to='API.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ManyToManyField(blank=True, null=True, to='API.tax', verbose_name='Налог'),
        ),
    ]
