# Generated by Django 5.0 on 2023-12-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_discount_order_remove_tax_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='API.item', verbose_name='Товар'),
        ),
    ]
