# Generated by Django 5.0 on 2023-12-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(blank=True, to='API.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ManyToManyField(blank=True, to='API.tax', verbose_name='Налог'),
        ),
    ]
