# Generated by Django 5.0 on 2023-12-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_item_currency_order_currency_alter_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('rub', 'Рубль'), ('usd', 'Доллар')], max_length=3, null=True, verbose_name='Валюта'),
        ),
    ]
